services:
  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:asusvivobook@localhost:5432/postgres
      - LOG_LEVEL=info
    network_mode: "host"
    deploy:
      replicas: 5
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redisdata:/data

volumes:
  redisdata: