export const handlers=new Map<string,(input:any)=>Promise<any>>([
    [
        "data.fetch",
        async(input:any)=>{
            return{
                rows:10
            }
        }
    ],
    [
        "data.process",
        async(input:any)=>{
            return{
                processed:true
            }
        }
    ],
    [
        "email.send",
        async(input:any)=>{
            return{
                sent:true
            }
        }
    ],
    [
        "dashboard.update",
        async(input:any)=>{
            return{
                updated:true
            }
        }
    ],
    [
        "all.fail",
        async(input:any)=>{
            throw new Error("error")
        }
    ],
    [
        "test.slow",
        async(input:any)=>{
            await new Promise((r)=>setTimeout(r,10000))
            return{
                slow:true
            }
        }
    ]
])